const ROLES = {
  PROPIETARIO: 'PROPIETARIO',
  INQUILINO: 'INQUILINO',
  ADMIN: 'ADMIN',
};

const PERMISOS = {
  //Auth y usuarios
  VER_PERFIL: [ROLES.PROPIETARIO, ROLES.INQUILINO, ROLES.ADMIN],
  
  //Contratos
  GESTIONAR_PROPIEDADES: [ROLES.PROPIETARIO, ROLES.ADMIN],
  CONSULTAR_PROPIEDAD_PROPIA: [ROLES.PROPIETARIO, ROLES.INQUILINO, ROLES.ADMIN],
  CREAR_CONTRATO: [ROLES.PROPIETARIO, ROLES.ADMIN],
  
  //Pagos
  SUBIR_COMPROBANTE_PAGO: [ROLES.INQUILINO],
  CONSULTAR_ESTADO_FINANCIERO: [ROLES.PROPIETARIO, ROLES.ADMIN],
  ASENTAR_COBRO: [ROLES.PROPIETARIO, ROLES.ADMIN],
  
  //Reclamos
  CREAR_RECLAMO: [ROLES.INQUILINO],
  ACTUALIZAR_ESTADO_RECLAMO: [ROLES.PROPIETARIO, ROLES.ADMIN],
  CONSULTAR_RECLAMOS: [ROLES.PROPIETARIO, ROLES.INQUILINO, ROLES.ADMIN],
};

module.exports = { ROLES, PERMISOS };
