const ROLES = {
  USUARIO: 'USUARIO',
  PROPIETARIO: 'PROPIETARIO',
  INQUILINO: 'INQUILINO',
  ADMINISTRADOR: 'ADMINISTRADOR',
};

const PERMISOS = {
  //Auth y usuarios
  VER_PERFIL: [ROLES.USUARIO, ROLES.PROPIETARIO, ROLES.INQUILINO, ROLES.ADMINISTRADOR],
  
  //Contratos
  GESTIONAR_PROPIEDADES: [ROLES.PROPIETARIO, ROLES.ADMINISTRADOR],
  CONSULTAR_PROPIEDAD_PROPIA: [ROLES.PROPIETARIO, ROLES.INQUILINO, ROLES.ADMINISTRADOR],
  CREAR_CONTRATO: [ROLES.PROPIETARIO, ROLES.ADMINISTRADOR],
  
  //Pagos
  SUBIR_COMPROBANTE_PAGO: [ROLES.INQUILINO],
  CONSULTAR_ESTADO_FINANCIERO: [ROLES.PROPIETARIO, ROLES.ADMINISTRADOR],
  ASENTAR_COBRO: [ROLES.PROPIETARIO, ROLES.ADMINISTRADOR],
  
  //Reclamos
  CREAR_RECLAMO: [ROLES.INQUILINO],
  ACTUALIZAR_ESTADO_RECLAMO: [ROLES.PROPIETARIO, ROLES.ADMINISTRADOR],
  CONSULTAR_RECLAMOS: [ROLES.PROPIETARIO, ROLES.INQUILINO, ROLES.ADMINISTRADOR],
};

module.exports = { ROLES, PERMISOS };
